apiVersion: argoproj.io/v1alpha1 # apps/v1 대신 argoproj.io/v1alpha1
kind: Rollout # Deployment 대신 Rollout
metadata:
  name: rollout-bluegreen-demo
  labels:
    app: rollout-bluegreen-demo
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-bluegreen-demo
  template:
    metadata:
      labels:
        app: rollout-bluegreen-demo
    spec:
      containers:
        - name: rollout-bluegreen-demo
          image: argoproj/rollouts-demo:blue
          # image: argoproj/rollouts-demo:green
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
  strategy:
    blueGreen:
      autoPromotionEnabled: false
      activeService: rollout-bluegreen-demo-active # 이전의 배포된 Blue 서비스
      previewService: rollout-bluegreen-demo-preview # 새롭게 배포될 Green 서비스

---
apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-demo-active
  labels:
    app: rollout-bluegreen-demo-active
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30090
  selector:
    app: rollout-bluegreen-demo

---
apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-demo-preview
  labels:
    app: rollout-bluegreen-demo-preview
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30091
  selector:
    app: rollout-bluegreen-demo

