apiVersion: v1
kind: Service
metadata:
  name: sample-yaml
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
  selector:
    run: sample-yaml